### ISSUE TITLE
Armor/Strength other stats of Player.cs are not decreased by monsters StatPackage during battle

### ISSUE THREAD

**Issue by Dud3ek** [JakubChecinski/GameC#1]
There were situations in which Monsters could not reduce armor(or any other) stat
of player even when we had it on value bigger than 0, it was like this because monster 
were applying their StatPackage class debuffs only to base stats of player, not stats
with items on him. That is why I needed to make changes here.

Examples:
Give player 50 armor base, monster applies debuffs which takes 20 armor from players armor (StatPackage armor damage)
Player has now 30 armor.

Give player 0 armor base and item that gives 40 armor, so player has 40 armor.
Monster applies 20 debuff to armor stat, player still has 40 because StatPackage of monster damage 
does not see buffs applied to players stats from items.

My solution: In file Player.cs - change code for Properties of Armor/Strength/Precision/MagicPower/Stamina to something like this:

public override int Armor
        {
            get
            {   if (armor + ArmorBuff < 0) return 0;
                else return armor + ArmorBuff; }
            set
            {
                armor = value;
            }
        }

Working program with this approach is downloaded by me to UPEL: Marcin Dudzik E&T

**Comment by JakubChecinski** [comment]
Thank you for describing this issue. The problem with changing getters and setters is that it would allow for debuff stacking during the gameplay - something which doesn't seem like a good idea to me. I think it's better to have a "base" underlying stat that cannot go below zero and only modify it temporarily for battle purposes.

So my current idea of how to fix this issue would be to modify the React method inside Player.cs - replace the UpdateStats by something like this:
                strength -= pack.StrengthDmg;
                armor -= pack.ArmorDmg;
                precision -= pack.PrecisionDmg;
                magicPower -= pack.MagicPowerDmg;
                if (Strength < 0) strength = -StrengthBuff;
                if (Armor < 0) armor = -ArmorBuff;
                if (Precision < 0) precision = -PrecisionBuff;
                if (MagicPower < 0) magicPower = -MagicPowerBuff;
