### ISSUE TITLE
Monster spawned on exit portal, portal disappears

### ISSUE THREAD

**Issue by PiotrWrobelAGH** [JakubChecinski/GameC#3]
It is possible to enter portal and get monster instead of portal at the other side. The bug was found in my version of code, which I have uploaded on UPEL, but I didn't change anything in the engine so I guess it exists in main version.

Bug preview:
https://youtu.be/m1a2uBGUCUE

Piotr Wróbel, EiT

**Comment by JakubChecinski** [comment]
Thank you. I have seen this bug a few times before, but unfortunately it seems to be very rare and difficult to reproduce/test. There was a small issue in the map creation code which could have occasionally interfered with portal generation - I fixed it now, so hopefully we don't see this bug again (but please let me know if you see it again).
